---
- name: Per-user group creation
  group:
    name: "{{ item.username }}"
  with_items: "{{ addusers.userlist }}"

- name: Add users
  user:
    name: "{{ item.username }}"
    group: "{{ item.primary_group }}"
    groups: "{{ item.groups | default([]) }}"
    password: "{{ item.password | password_hash('sha512') }}"
  with_items: "{{ addusers.userlist }}"

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Add sudoers users to wheel group
  user:
    name: "{{ item }}"
    groups: wheel
    append: yes
  with_items: "{{ addusers.sudoers }}"