---
awx_web_image: ansible/awx_web
awx_web_port: 80
awx_task_image: ansible/awx_task
awx_memcached_image: memcached
awx_rabbitmq_image: rabbitmq
awx_rabbitmq_user: guest
awx_rabbitmq_pass: guest
awx_postgres_image: postgres
awx_postgres_user: awx
awx_postgres_pass: changeme
awx_folder: /opt/awx
awx_secret_key: changeme
awx_products: []
awx_version: 1.0.2
awx_memcached_version: 1.5.3
awx_rabbitmq_version: 3.7.0
awx_postgres_version: 10.1
