---
- name: Start containers
  include_tasks: containers.yml

- name: Wait for AWX to start
  uri:
    url: "http://localhost:{{ awx_web_port }}/api/v2/authtoken/"
    method: POST
    body: '{"username":"admin","password":"password"}'
    headers:
      Content-Type: application/json
  register: result
  until: result.status == 200 and not result.redirected
  retries: 180
  delay: 10
