---
- hosts: all
  roles:
    - prereq
    - docker
    - addusers
    - ajenti
  tags: all

- hosts: all
  roles:
    - ajenti-plugins
  tags: update

- hosts: master
  roles:
    - awx
  tags: master
