---
- hosts: all
  roles:
    - prereq
    - addusers
  tags:
    - prereq

- hosts: all
  roles:
    - ajenti
  tags: ajenti

- hosts: all
  roles:
    - cockpit
  tags: cockpit

- hosts: all
  roles:
    - webmin
  tags: webmin

- hosts: all
  roles:
    - ajenti-plugins
  tags:
    - ajenti
    - update

- hosts: all
  roles:
    - cockpit-plugins
  tags:
    - cockpit
    - update

- hosts: all
  roles:
    - webmin-plugins
  tags:
    - webmin
    - update

- hosts: master
  roles:
    - docker
    - awx
  tags: awx
