- name: install cockpit
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - cockpit
    - cockpit-system
    - cockpit-storaged
    - cockpit-machines
    - cockpit-packagekit
    - cockpit-pcp
    - cockpit-selinux
    - cockpit-subscriptions
    - cockpit-docker
#    - cockpit-kdump
#    - cockpit-kubernetes
    - cockpit-dashboard
    - cockpit-sosreport
    - cockpit-ws
    - cockpit-tests

- name: enable Cockpit service
  systemd:
    name: cockpit.socket
    enabled: yes
    state: started
    daemon_reload: yes
