- name: Remove existing plugins
  file:
    path: "{{ webminplugins.plugindir }}"
    state: absent

- name: Create destination directory for plugins
  file:
    path: "{{ webminplugins.plugindir }}"
    state: directory

- name: Copy plugins
  copy:
    src: ../../../plugins/webmin/
    dest: "{{ webminplugins.plugindir }}"
  notify: restart webmin
